package_assets: off
javascripts:
  app:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/application.js
  admin:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/jquery.tagsinput.min.js
    - public/javascripts/admin.js
stylesheets:
  app:
    - public/stylesheets/app.css
    - public/stylesheets/jquery-ui.css
  admin:
    - public/stylesheets/admin.css
    - public/stylesheets/jquery.tagsinput.css