--- 
javascripts: 
- base: 
  - jquery_ujs
  - application
  - directorio
- admin_package:
  - jquery_ujs
  - admin
stylesheets: 
- base: 
  - ../../tmp/stylesheets/screen
  - ../../tmp/stylesheets/print
  - jquery-ui
- admin_package:
  - jquery-ui
  - admin
