package_assets: off
javascripts:
  app:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/application.js
  admin_package:
    - public/javascripts/jquery_ujs.js
    - public/javascripts/admin.js
stylesheets:
  app:
    - public/stylesheets/screen.css
    - public/stylesheets/print.css
    - public/stylesheets/jquery-ui.css
  admin_package:
    - public/stylesheets/jquery-ui.css
    - public/stylesheets/admin.css