server: &server
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: jparbros
  password:

development:
  <<: *server
  database: promesometro_development

test: &test
  <<: *server
  database: promesometro_test

production:
  <<: *server
  database: promesometro